#!/bin/sh

set -Cf
IFS="$(printf '%b_' '\n')"; IFS="${IFS%_}"

image() {
    if [ -f "$1" ] && [ -n "$DISPLAY" ] && [ -z "$WAYLAND_DISPLAY" ] && command -v ueberzug >/dev/null 2>&1; then
        printf '{"action": "add", "identifier": "PREVIEW", "x": "%s", "y": "%s", "width": "%s", "height": "%s", "scaler": "contain", "path": "%s"}\n' "$4" "$5" "$(($2-1))" "$(($3-1))" "$1" > "$FIFO_UEBERZUG"
    else
        mediainfo "$6"
    fi
}

case "$(file --dereference --brief --mime-type -- "$1")" in
    image/avif)
        CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf "%n\0%i\0%F\0%s\0%W\0%Y" -- "$(readlink -f "$1")" | md5sum)" CACHE="${CACHE%% *}"
        [ ! -f "$CACHE.jpg" ] && magick "$1" "$CACHE.jpg"
        image "$CACHE.jpg" "$2" "$3" "$4" "$5" "$1"
        ;;

    image/vnd.djvu)
        CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf "%n\0%i\0%F\0%s\0%W\0%Y" -- "$(readlink -f "$1")" | md5sum)" CACHE="${CACHE%% *}"
        [ ! -f "$CACHE.jpg" ] && djvused "$1" -e 'select 1; save-page-with /dev/stdout' | magick -density 200 - "$CACHE.jpg" > /dev/null 2>&1
        image "$CACHE.jpg" "$2" "$3" "$4" "$5" "$1"
        ;;

    image/svg+xml)
        CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf "%n\0%i\0%F\0%s\0%W\0%Y" -- "$(readlink -f "$1")" | md5sum)" CACHE="${CACHE%% *}"
        [ ! -f "$CACHE.png" ] && inkscape --convert-dpi-method=none -o "$CACHE.png" --export-overwrite -D --export-png-color-mode=RGBA_16 "$1"
        image "$CACHE.png" "$2" "$3" "$4" "$5" "$1"
        ;;

    image/x-xcf)
        CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf "%n\0%i\0%F\0%s\0%W\0%Y" -- "$(readlink -f "$1")" | md5sum)" CACHE="${CACHE%% *}"
        [ ! -f "$CACHE.jpg" ] && magick "$1[0]" "$CACHE.jpg"
        image "$CACHE.jpg" "$2" "$3" "$4" "$5" "$1"
        ;;

    image/*) image "$1" "$2" "$3" "$4" "$5" "$1";;

    text/html) lynx -width="$4" -display_charset=utf-8 -dump "$1";;

    text/troff) man ./ "$1" | col -b;;

    text/*  | */xml | application/json | application/x-ndjson) bat -p --theme ansi --terminal-width "$((4-2))" -f "$1";;

    audio/* | application/octet-stream) mediainfo "$1" || exit 1;;

    video/*)
        CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | md5sum)" CACHE="${CACHE%% *}"
        [ ! -f "$CACHE" ] && ffmpegthumbnailer -i "$1" -o "$CACHE" -s 0
        image "$CACHE" "$2" "$3" "$4" "$5" "$1"
        ;;

    */pdf)
        CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | md5sum)" CACHE="${CACHE%% *}"
        [ ! -f "$CACHE.jpg" ] && pdftoppm -jpeg -f 1 -singlefile "$1" "$CACHE"
        image "$CACHE.jpg" "$2" "$3" "$4" "$5" "$1"
        ;;

    application/zip|\
    application/x-7z-compressed|\
    application/vnd.rar|application/x-rar|\
    application/x-tar|\
    application/gzip|application/x-gzip|\
    application/x-bzip2|\
    application/x-xz|\
    application/zstd|application/x-zstd|\
    application/x-lz4|\
    application/x-lzip|\
    application/vnd.debian.binary-package|application/x-debian-package|\
    application/x-rpm|\
    application/vnd.android.package-archive|\
    application/java-archive|\
    application/x-iso9660-image|\
    application/x-cpio|\
    application/vnd.ms-cab-compressed|application/x-cab)
        # list contents but only grab the list and not the copyright notice
        7z l "$1" | awk '/^\s*Date[[:space:]]+Time[[:space:]]+Attr/ {p=1; print; next}
                          p && /^-------------------/ {d++; if (d<=2) print; next
                          p && /^[0-9]{4}-[0-9]{2}-[0-9]{2}/ {print}
                          d>=2 {exit}'
        ;;
    *) mediainfo "$1";;
esac
exit 1
