#!/bin/sh

# Use neovim for vi/vim if present:
[ -x "$(command -v nvim)" ] && alias vi="nvim" vim="nvim" vimdiff="nvim -d" neogit="nvim +Neogit"

# Alias magit if emacs is installed
[ -x "$(command -v emacs)" ] && alias magit="emacs --no-window-system --execute=\"(magit-status)\""

# Use exa for ls if present (if not just colorize ls):
if [ -x "$(command -v exa)" ]; then
	alias ls="exa --group-directories-first --git"
else
	alias ls="ls -hNr --color=auto --group-directories-first"
fi

# Use $XINITRC variable if file exists:
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands:
for command in mount umount pacman su fdisk dd systemctl; do
	alias $command="sudo $command"
done; unset command

# Use kitty's own ssh when using kitty:
[ "$TERM" = "xterm-kitty" ] && alias ssh="kitten ssh"

# Unnecessary bling:
command -v spark lolcat >/dev/null 2>&1 && alias clear='echo -en "\x1b[2J\x1b[1;1H"; echo; echo; seq 1 $(tput cols) | sort -R | spark | lolcat; echo; echo'

# Verbosity and settings that you pretty much just always are going to want:
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	nsxiv="nsxiv -b" \
	history="history 0" \
	cw="wc -w" \
	lc="wc -l" \
	du="du -hs" \
	df="df -h"

# Colorize commmands when possible:
alias \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	ip="ip -color=auto"

# These common commands are just too long! Abbreviate them:
alias \
	c="clear" \
	v="vim" \
	z="zathura" \
	lf="lfub" \
	ll="ls -la" \
	unrar="unrar-free" \
	update-grub="sudo grub-mkconfig -o /boot/grub/grub.cfg" \
	pong="ping 4.2.2.4" \
	qq="proxychains -q"
	
