#!/bin/zsh

# profile file. Environmental variables are set here.

# Adds `~/.local/bin` and it's sub-directories to $PATH
export PATH="$PATH$(find ~/.local/bin -type d -printf ":%p")"

# Default programs:
export EDITOR="nvim"
export TERMINAL="alacritty"
export BROWSER="brave"
export WM="hyprland"

# bat as manpager:
export MANROFFOPT="-c"
export MANPAGER="/bin/sh -c 'col -bx | bat -l man -p'"
# Run the following command if you want to reset the manpager:
# `unset MANPAGER`

# `~/` Clean-up:
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XINITRC="$XDG_CONFIG_HOME/x11/xinitrc"
# export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"
export ERRFILE="$XDG_CACHE_HOME/x11/xsession-errors"
export INPUTRC="$XDG_CONFIG_HOME/shell/inputrc"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc-2.0"
export LESSHISTFILE="-"
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export CUDA_CACHE_PATH="$XDG_CACHE_HOME/nv"
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/pass"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export PYTHONSTARTUP="$XDG_CONFIG_HOME/python/pythonrc"
export TERMINFO="$XDG_DATA_HOME/terminfo"
export TERMINFO_DIRS="$XDG_DATA_HOME/terminfo:/usr/share/terminfo"
export _JAVA_OPTIONS="-Djava.util.prefs.userRoot=\"$XDG_CONFIG_HOME/java\" -Djavafx.cachedir=\"$XDG_CACHE_HOME/openjfx\""

# Some settings:
# export TERM=xterm-256color # already doing this within `st`
export SUDO_ASKPASS="$HOME/.local/bin/dmenupass"
export QT_QPA_PLATFORMTHEME="qt5ct"
export LESS=-R
export LESS_TERMCAP_mb="$(printf '%b' '\e[1;31m')"
export LESS_TERMCAP_md="$(printf '%b' '\e[1;36m')"
export LESS_TERMCAP_me="$(printf '%b' '\e[0m')"
export LESS_TERMCAP_so="$(printf '%b' '\e[01;44;33m')"
export LESS_TERMCAP_se="$(printf '%b' '\e[0m')"
export LESS_TERMCAP_us="$(printf '%b' '\e[1;32m')"
export LESS_TERMCAP_ue="$(printf '%b' '\e[0m')"
export LESSOPEN="| /usr/bin/highlight -O ansi %s 2>/dev/null"
# export AWT_TOOLKIT="MToolkit wmname LG3D" # May have to install `wmname`
export _JAVA_AWT_WM_NONREPARENTING=1

# Start graphical server on user's first tty if not already running.
case "$WM" in
    "dwm")      [ "$(tty)" = "/dev/tty1" ] && ! pidof -s Xorg     >/dev/null 2>&1 && export STATUSBAR="dwmblocks" && exec startx "$XINITRC";;
    "hyprland") [ "$(tty)" = "/dev/tty1" ] && ! pidof -s hyprland >/dev/null 2>&1 && export STATUSBAR="waybar"    && exec hyprland;;
esac
