#!/bin/sh

# This file runs when you log into a graphical session.
# If you use startx/xinit like a chad, this file will also be sourced.

setsid -f xrdb "$HOME/.config/x11/xresources"

xset r rate 300 50

autostart="xcompmgr screenres nm-applet numlockx taptoclick unclutter dunst setbg"
for p in $autostart; do
    pidof -s "$p" || setsid -f "$p"
done
