#!/bin/sh

# This file runs when you log into a graphical session.
# If you use startx/xinit like a chad, this file will also be sourced.

setsid -f xrdb "$HOME/.config/x11/xresources"

# Keyboard tweaks:
xset r rate 300 50
xmodmap "$HOME/.config/x11/xmodmaprc"

autostart="xcompmgr screenres nm-applet blueman-applet bluemon numlockx taptoclick unclutter dunst setbg"
for p in $autostart; do
    pidof -sx "$p" || setsid -f "$p"
done >/dev/null 2>&1
