[mgr]
    ratio = [1, 2, 3]
    show_hidden = true
    show_symlink = false

[opener]
    play = [{ run = "open %s; clear", block = true }]
    edit = [{ run = "open %s; clear", block = true }]
    open = [{ run = "open %s; clear", block = true }]
